# Generated by Django 5.1.4 on 2025-01-05 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to='category_icons/'),
        ),
    ]
