# Generated by Django 5.1.4 on 2025-01-05 20:10

import server.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_alter_category_options_category_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='server_images/', validators=[server.models.validate_image_formant]),
        ),
    ]
